# Generated by Django 5.0.7 on 2026-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subject', models.CharField(blank=True, choices=[('رياضيات', 'رياضيات'), ('فيزياء', 'فيزياء'), ('كيمياء', 'كيمياء'), ('أحياء', 'أحياء'), ('فرنسية', 'فرنسية'), ('عربية', 'عربية'), ('إنجليزية', 'إنجليزية'), ('تاريخ', 'تاريخ'), ('جغرافيا', 'جغرافيا'), ('فلسفة', 'فلسفة'), ('اقتصاد', 'اقتصاد')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Deckprogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('total_flashcards', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
