# Generated by Django 5.2.17 on 2026-09-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_add_uuid_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='grade',
        ),
    ]
