# Generated by Django 5.2.17 on 2026-10-03 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'id'],
                'constraints': [models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='planner_year_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('SCHOOL', 'School'), ('EXTERNAL_TUTORING', 'External tutoring'), ('OTHER_FIXED', 'Other fixed'), ('PROTECTED_BLOCK', 'Protected block')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('suspended_by_periods', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='users.student')),
            ],
            options={
                'ordering': ['student', 'weekday', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommitmentException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('MOVED', 'Moved')], max_length=10)),
                ('new_start', models.TimeField(blank=True, null=True)),
                ('new_end', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='planner.commitment')),
            ],
            options={
                'ordering': ['commitment', 'date'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlannerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('timezone', models.CharField(default='Africa/Algiers', max_length=64)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('preferred_period', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NONE', 'No preference')], default='NONE', max_length=16)),
                ('max_focus_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('session_length_preference', models.CharField(choices=[('SHORT', 'Short'), ('MEDIUM', 'Medium'), ('LONG', 'Long'), ('NONE', 'No preference')], default='NONE', max_length=8)),
                ('daily_study_target_minutes', models.PositiveIntegerField(default=120)),
                ('week_start', models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], default='SUNDAY', max_length=10)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planner_profile', to='users.student')),
            ],
            options={
                'verbose_name_plural': 'Student planner profiles',
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('TRIMESTER', 'Trimester'), ('HOLIDAY', 'Holiday'), ('EXAM_PERIOD', 'Exam period'), ('SPECIAL_DAY', 'Special day')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('applies_to_levels', models.JSONField(blank=True, default=list)),
                ('suspends_school', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('source_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='planner.academicyear')),
            ],
            options={
                'ordering': ['start_date', 'id'],
                'indexes': [models.Index(fields=['academic_year', 'start_date'], name='planner_aca_academi_bb0664_idx'), models.Index(fields=['kind'], name='planner_aca_kind_45b3cb_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='planner_period_end_on_or_after_start')],
            },
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['student', 'weekday'], name='planner_com_student_a39340_idx'),
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='planner_commitment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.CheckConstraint(check=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='planner_commitment_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='planner_commitment_validity_order'),
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'SCHOOL'), _negated=True), ('suspended_by_periods', True), _connector='OR'), name='planner_school_commitment_suspendable'),
        ),
        migrations.AddConstraint(
            model_name='commitmentexception',
            constraint=models.UniqueConstraint(fields=('commitment', 'date'), name='planner_one_exception_per_commitment_date'),
        ),
        migrations.AddConstraint(
            model_name='commitmentexception',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'MOVED'), _negated=True), models.Q(('new_start__isnull', False), ('new_end__isnull', False)), _connector='OR'), name='planner_moved_exception_needs_times'),
        ),
        migrations.AddConstraint(
            model_name='commitmentexception',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'CANCELLED'), _negated=True), models.Q(('new_start__isnull', True), ('new_end__isnull', True)), _connector='OR'), name='planner_cancelled_exception_has_no_times'),
        ),
        migrations.AddConstraint(
            model_name='commitmentexception',
            constraint=models.CheckConstraint(check=models.Q(('new_start__isnull', True), ('new_end__isnull', True), ('new_end__gt', models.F('new_start')), _connector='OR'), name='planner_exception_new_end_after_new_start'),
        ),
        migrations.AddConstraint(
            model_name='studentplannerprofile',
            constraint=models.CheckConstraint(check=models.Q(('max_focus_minutes__isnull', True), ('max_focus_minutes__gte', 1), _connector='OR'), name='planner_profile_max_focus_gte_1'),
        ),
    ]
