# Generated by Django 5.2.17 on 2026-10-03 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ONBOARDING', 'Onboarding')], default='MANUAL', max_length=12),
        ),
        migrations.CreateModel(
            name='PlannerExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('exam_date', models.DateField()),
                ('exam_type', models.CharField(choices=[('TEST', 'Test'), ('EXAM', 'Exam'), ('MOCK', 'Mock'), ('BAC', 'BAC')], max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_exams', to='users.student')),
            ],
            options={
                'ordering': ['exam_date', 'id'],
                'indexes': [models.Index(fields=['student', 'exam_date'], name='planner_pla_student_767e6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('WEAK', 'Weak'), ('AVERAGE', 'Average'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very good')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_confidences', to='users.student')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject'), name='planner_one_confidence_per_student_subject')],
            },
        ),
    ]
