# Generated by Django 5.2.17 on 2026-10-03 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_commitment_origin_plannerexam_subjectconfidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogyRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('applies_to_level', models.CharField(blank=True, default='', max_length=120)),
                ('applies_to_stream', models.CharField(blank=True, default='', max_length=120)),
                ('json', models.JSONField(default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version', 'id'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='planner_unique_ruleset_name_version')],
            },
        ),
        migrations.CreateModel(
            name='SubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('level', models.CharField(blank=True, default='', max_length=120)),
                ('stream', models.CharField(blank=True, default='', max_length=120)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('weekly_target_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('source_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level', 'stream', 'subject', 'id'],
                'indexes': [models.Index(fields=['level', 'stream', 'subject'], name='planner_sub_level_a66113_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject', 'level', 'stream'), name='planner_unique_subject_config_scope')],
            },
        ),
    ]
