# Generated by Django 5.2.17 on 2026-10-03 14:48

import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_pedagogyruleset_subjectconfig'),
        ('schedule', '0005_personalscheduleitem_activity_type_and_more'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        CreateExtension('btree_gist'),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('input_hash', models.CharField(max_length=64)),
                ('trigger', models.CharField(choices=[('MANUAL', 'Manual'), ('ONBOARDING', 'Onboarding'), ('SCHEDULED', 'Scheduled'), ('EXAM', 'Exam')], default='MANUAL', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='planner.pedagogyruleset')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='users.student')),
            ],
            options={
                'ordering': ['-version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlannedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('activity_type', models.CharField(max_length=32)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('origin', models.CharField(choices=[('SYSTEM', 'System'), ('STUDENT', 'Student')], default='SYSTEM', max_length=8)),
                ('state', models.CharField(choices=[('PLANNED', 'Planned'), ('DONE', 'Done'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_session', to='schedule.personalscheduleitem')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='planner.plannedsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sessions', to='users.student')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planner.studyplan')),
            ],
            options={
                'ordering': ['start_dt', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('start_min', models.PositiveSmallIntegerField()),
                ('end_min', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(blank=True, default='', max_length=150)),
                ('activity_type', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombstones', to='planner.plannedsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tombstones', to='users.student')),
            ],
            options={
                'ordering': ['student', 'date', 'start_min'],
                'indexes': [models.Index(fields=['student', 'date'], name='planner_ses_student_7ca5a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date', 'start_min'), name='planner_unique_tombstone_slot'), models.CheckConstraint(check=models.Q(('end_min__gt', models.F('start_min'))), name='planner_tombstone_end_after_start')],
            },
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['student', '-created_at'], name='planner_stu_student_e7021f_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(fields=('student', 'version'), name='planner_unique_plan_version_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.CheckConstraint(check=models.Q(('window_end__gte', models.F('window_start'))), name='planner_plan_window_order'),
        ),
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['student', 'start_dt'], name='planner_pla_student_cbfeba_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['student', 'state'], name='planner_pla_student_3dd2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['plan'], name='planner_pla_plan_id_dbfd4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannedsession',
            constraint=models.CheckConstraint(check=models.Q(('end_dt__gt', models.F('start_dt'))), name='planner_planned_session_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='plannedsession',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('state', 'PLANNED')), expressions=[(models.F('student'), '='), (models.Func(models.F('start_dt'), models.F('end_dt'), function='tstzrange'), '&&')], name='planner_no_overlapping_planned_sessions'),
        ),
    ]
