# Generated by Django 5.2.17 on 2026-10-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_studyplan_plannedsession_sessiontombstone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedsession',
            name='state',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('DONE', 'Done'), ('PARTIAL', 'Partial'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=10),
        ),
    ]
