# Generated by Django 5.2.17 on 2026-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_plannedsession_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='trigger',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ONBOARDING', 'Onboarding'), ('SCHEDULED', 'Scheduled'), ('EXAM', 'Exam'), ('COMMITMENT', 'Commitment change'), ('SESSION_MISSED', 'Session missed'), ('WEEKLY', 'Weekly roll'), ('AVAILABILITY', 'Availability change')], default='MANUAL', max_length=16),
        ),
    ]
