# Generated by Django 5.2.17 on 2026-10-03 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_studyplan_trigger'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(blank=True, default='', max_length=120)),
                ('stream', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('source_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='planner.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'level', 'stream', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='planner.curriculumversion')),
            ],
            options={
                'ordering': ['curriculum', 'subject', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='planner.chapter')),
            ],
            options={
                'ordering': ['chapter', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COVERED', 'Covered'), ('SHAKY', 'Shaky'), ('MASTERED', 'Mastered')], default='NOT_STARTED', max_length=12)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='users.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='planner.topic')),
            ],
            options={
                'ordering': ['student', 'topic', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_ar', models.CharField(blank=True, default='', max_length=500)),
                ('text_fr', models.CharField(blank=True, default='', max_length=500)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='planner.topic')),
            ],
            options={
                'ordering': ['topic', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='plannerexam',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='planner.topic'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('academic_year', 'level', 'stream'), name='planner_unique_curriculum_scope'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('curriculum', 'subject', 'order'), name='planner_unique_chapter_order'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('chapter', 'order'), name='planner_unique_topic_order'),
        ),
        migrations.AddConstraint(
            model_name='studenttopicprogress',
            constraint=models.UniqueConstraint(fields=('student', 'topic'), name='planner_unique_topic_progress'),
        ),
    ]
