# Generated by Django 5.0.7 on 2026-10-06 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_curriculumversion_chapter_topic_studenttopicprogress_and_more'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPlanningMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('mode', models.CharField(choices=[('AUTO', 'Auto'), ('MORE', 'More'), ('TRACKING_ONLY', 'Tracking only')], default='AUTO', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_planning_modes', to='users.student')),
            ],
            options={
                'ordering': ['student', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='SubjectImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('level', models.CharField(blank=True, default='', max_length=120)),
                ('stream', models.CharField(blank=True, default='', max_length=120)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tier', models.CharField(choices=[('CORE', 'Core'), ('STANDARD', 'Standard'), ('LIGHT', 'Light')], default='STANDARD', max_length=8)),
                ('verified', models.BooleanField(default=False)),
                ('source_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_importances', to='planner.academicyear')),
            ],
            options={
                'verbose_name_plural': 'subject importance',
                'ordering': ['level', 'stream', 'subject', 'id'],
                'indexes': [models.Index(fields=['level', 'stream', 'subject'], name='planner_sub_level_d7992d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectimportance',
            constraint=models.UniqueConstraint(fields=('subject', 'level', 'stream'), name='planner_unique_subject_importance_scope'),
        ),
        migrations.AddConstraint(
            model_name='subjectimportance',
            constraint=models.CheckConstraint(check=models.Q(('coefficient__isnull', True), ('coefficient__gte', 0), _connector='OR'), name='planner_subject_importance_coefficient_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='subjectplanningmode',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='planner_unique_subject_planning_mode'),
        ),
    ]
