# Generated by Django 5.0.7 on 2026-10-06 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_quizattempt_adaptive_state'),
        ('planner', '0008_subjectplanningmode_subjectimportance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedsession',
            name='practice_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_sessions', to='assessment.quiz'),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_sessions', to='planner.topic'),
        ),
    ]
