# Generated by Django 5.0.7 on 2026-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_plannedsession_practice_quiz_plannedsession_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='trigger',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ONBOARDING', 'Onboarding'), ('SCHEDULED', 'Scheduled'), ('EXAM', 'Exam'), ('COMMITMENT', 'Commitment change'), ('SESSION_MISSED', 'Session missed'), ('WEEKLY', 'Weekly roll'), ('AVAILABILITY', 'Availability change'), ('MASTERY', 'Mastery change')], default='MANUAL', max_length=16),
        ),
    ]
