# Generated by Django 5.2.17 on 2026-10-08 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_studyplan_trigger'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCurrentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentplannerprofile',
            name='level',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='studentplannerprofile',
            name='stream',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='mastery_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='minutes_studied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='trimester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.CheckConstraint(condition=models.Q(('trimester__gte', 1), ('trimester__lte', 3)), name='planner_topic_trimester_range'),
        ),
        migrations.AddField(
            model_name='subjectcurrenttopic',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_topics', to='users.student'),
        ),
        migrations.AddField(
            model_name='subjectcurrenttopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_for_students', to='planner.topic'),
        ),
        migrations.AddConstraint(
            model_name='subjectcurrenttopic',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='planner_one_current_topic_per_subject'),
        ),
    ]
