# Generated by Django 5.0.7 on 2026-08-28 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_examdate_scheduledtask_studentblackout_and_more'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalscheduleitem',
            name='target_prep_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_minutes', models.PositiveSmallIntegerField(default=25)),
                ('short_break_minutes', models.PositiveSmallIntegerField(default=5)),
                ('long_break_minutes', models.PositiveSmallIntegerField(default=15)),
                ('pomodoros_until_long_break', models.PositiveSmallIntegerField(default=4)),
                ('auto_start_breaks', models.BooleanField(default=True)),
                ('auto_start_focus', models.BooleanField(default=False)),
                ('daily_goal_minutes', models.PositiveIntegerField(default=120)),
                ('timezone_offset_minutes', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pomodoro settings',
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('local_date', models.DateField()),
                ('planned_pomodoros', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_pomodoros', models.PositiveSmallIntegerField(default=0)),
                ('total_focus_seconds', models.PositiveIntegerField(default=0)),
                ('total_break_seconds', models.PositiveIntegerField(default=0)),
                ('interruptions', models.PositiveSmallIntegerField(default=0)),
                ('focus_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='schedule.personalscheduleitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FOCUS', 'Focus'), ('SHORT_BREAK', 'Short Break'), ('LONG_BREAK', 'Long Break')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('ABANDONED', 'Abandoned')], default='RUNNING', max_length=20)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('planned_seconds', models.PositiveIntegerField()),
                ('accumulated_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('last_resumed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('interruptions', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='schedule.studysession')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DailyProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('focus_minutes', models.PositiveIntegerField(default=0)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('completed_pomodoros', models.PositiveSmallIntegerField(default=0)),
                ('sessions_count', models.PositiveSmallIntegerField(default=0)),
                ('interruptions', models.PositiveSmallIntegerField(default=0)),
                ('tasks_completed', models.PositiveSmallIntegerField(default=0)),
                ('goal_minutes', models.PositiveIntegerField(default=0)),
                ('goal_met', models.BooleanField(default=False)),
                ('avg_focus_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_productivity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily productivity',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='schedule_da_user_id_59b57f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyproductivity',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='schedule_one_rollup_per_user_day'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'started_at'], name='schedule_st_user_id_8757dc_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'local_date'], name='schedule_st_user_id_2c4d84_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'status'], name='schedule_st_user_id_ac0222_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'subject'], name='schedule_st_user_id_2b0271_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'PAUSED'])), fields=('user',), name='schedule_one_open_study_session_per_user'),
        ),
        migrations.AddConstraint(
            model_name='pomodorointerval',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='schedule_interval_sequence_per_session'),
        ),
    ]
