# Generated by Django 5.2.17 on 2026-10-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_pomodorointerval_action_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalscheduleitem',
            name='activity_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='personalscheduleitem',
            name='planned_session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='personalscheduleitem',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PLANNER', 'Planner')], default='MANUAL', max_length=8),
        ),
    ]
