# Generated by Django 5.2.17 on 2026-09-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_add_uuid_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentblackout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstudypreferences',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExamDate',
        ),
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
        migrations.DeleteModel(
            name='StudentBlackout',
        ),
        migrations.DeleteModel(
            name='UserStudyPreferences',
        ),
    ]
