# Generated by Django 5.2.17 on 2026-09-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riffaaAi', '0003_add_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
