# Generated by Django 5.2.17 on 2026-10-01 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('timezone', models.CharField(default='Africa/Algiers', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User tracking settings',
            },
        ),
        migrations.AddField(
            model_name='activityevent',
            name='client_event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('user', 'client_event_id'), name='uniq_activity_user_client_event'),
        ),
        migrations.AddField(
            model_name='usertrackingsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
