# Generated by Django 5.2.17 on 2026-10-01 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_surveyattempt_options_and_more'),
        ('tracking', '0002_usertrackingsettings_activityevent_client_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metric', models.CharField(choices=[('WATCH_MINUTES', 'Watch minutes'), ('LESSONS_COMPLETED', 'Lessons completed'), ('QUIZZES_SUBMITTED', 'Quizzes submitted')], max_length=32)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=8)),
                ('target', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_goals', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalPeriodResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('met', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_results', to='tracking.studygoal')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddIndex(
            model_name='studygoal',
            index=models.Index(fields=['user', 'is_active'], name='tracking_st_user_id_654c53_idx'),
        ),
        migrations.AddIndex(
            model_name='studygoal',
            index=models.Index(fields=['user', 'metric', 'period'], name='tracking_st_user_id_41d5fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='studygoal',
            constraint=models.CheckConstraint(check=models.Q(('target__gte', 1)), name='goal_target_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='studygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('is_active', True)), fields=('user', 'metric', 'period'), name='uniq_active_goal_all_courses'),
        ),
        migrations.AddConstraint(
            model_name='studygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'metric', 'period', 'course'), name='uniq_active_goal_per_course'),
        ),
        migrations.AddIndex(
            model_name='goalperiodresult',
            index=models.Index(fields=['goal', 'met'], name='tracking_go_goal_id_732794_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalperiodresult',
            constraint=models.UniqueConstraint(fields=('goal', 'period_start'), name='uniq_goal_period_result'),
        ),
    ]
