# Generated by Django 5.2.17 on 2026-10-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_studygoal_goalperiodresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='course_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
