# Generated by Django 5.2.17 on 2026-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_activityevent_course_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='study_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
