# Generated by Django 5.2.17 on 2026-10-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_dailyactivity_study_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='is_scheduled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='source_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='source_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studygoal',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studygoal',
            name='metric',
            field=models.CharField(choices=[('WATCH_MINUTES', 'Watch minutes'), ('STUDY_MINUTES', 'Study minutes'), ('LESSONS_COMPLETED', 'Lessons completed'), ('QUIZZES_SUBMITTED', 'Quizzes submitted')], max_length=32),
        ),
    ]
