# Generated by Django 5.2.17 on 2026-10-01 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_surveyattempt_options_and_more'),
        ('tracking', '0006_activityevent_is_scheduled_activityevent_source_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studygoal',
            name='uniq_active_goal_all_courses',
        ),
        migrations.RemoveConstraint(
            model_name='studygoal',
            name='uniq_active_goal_per_course',
        ),
        migrations.AddConstraint(
            model_name='studygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('is_active', True), ('subject__isnull', True)), fields=('user', 'metric', 'period'), name='uniq_active_goal_all_courses'),
        ),
        migrations.AddConstraint(
            model_name='studygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('is_active', True), ('subject__isnull', True)), fields=('user', 'metric', 'period', 'course'), name='uniq_active_goal_per_course'),
        ),
        migrations.AddConstraint(
            model_name='studygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('is_active', True), ('subject__isnull', False)), fields=('user', 'metric', 'period', 'subject'), name='uniq_active_goal_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='studygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('is_active', True), ('subject__isnull', False)), fields=('user', 'metric', 'period', 'course', 'subject'), name='uniq_active_goal_course_subject'),
        ),
    ]
