# Generated by Django 5.2.17 on 2026-10-02 00:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_remove_studygoal_uniq_active_goal_all_courses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metric', models.CharField(choices=[('MINUTES', 'Study minutes'), ('HOURS', 'Study hours')], default='MINUTES', max_length=16)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=8)),
                ('target', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('weekday_overrides', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='tracking_go_user_id_23c9b4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('period', 'DAILY')), fields=('user',), name='uniq_active_daily_goal_per_user')],
            },
        ),
    ]
