# Generated by Django 5.0.7 on 2024-08-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
