# Generated by Django 5.0.7 on 2026-10-06 16:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0007_curriculumversion_chapter_topic_studenttopicprogress_and_more'),
        ('users', '0004_fieldofstudy_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Misconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_fr', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='planner.topic')),
            ],
            options={
                'ordering': ['topic', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('MCQ_SINGLE', 'Single choice'), ('MCQ_MULTI', 'Multiple choice'), ('TRUE_FALSE', 'True / false'), ('NUMERIC', 'Numeric')], max_length=12)),
                ('prompt_ar', models.TextField(blank=True, default='')),
                ('prompt_fr', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assessment/questions/')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('est_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('explanation_ar', models.TextField(blank=True, default='')),
                ('explanation_fr', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
                ('is_sample', models.BooleanField(default=False)),
                ('source_note', models.CharField(blank=True, default='', max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_questions', to='users.teacher')),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='planner.curriculumversion')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='planner.learningobjective')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='planner.topic')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumericAnswerSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('correct_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tolerance_abs', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('tolerance_rel', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('accepted_units', models.JSONField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_spec', to='assessment.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('text_ar', models.TextField(blank=True, default='')),
                ('text_fr', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('misconception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='assessment.misconception')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='misconception',
            constraint=models.UniqueConstraint(fields=('topic', 'code'), name='assessment_unique_misconception_code'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'status'], name='assessment__topic_i_24a9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status'], name='assessment__status_1c4512_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author'], name='assessment__author__245e69_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='assessment_question_difficulty_range'),
        ),
        migrations.AddConstraint(
            model_name='numericanswerspec',
            constraint=models.CheckConstraint(check=models.Q(('tolerance_abs__isnull', True), ('tolerance_abs__gte', 0), _connector='OR'), name='assessment_numeric_tolerance_abs_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='numericanswerspec',
            constraint=models.CheckConstraint(check=models.Q(('tolerance_rel__isnull', True), ('tolerance_rel__gte', 0), _connector='OR'), name='assessment_numeric_tolerance_rel_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='assessment_unique_option_order'),
        ),
    ]
