# Generated by Django 5.0.7 on 2026-10-06 16:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('planner', '0007_curriculumversion_chapter_topic_studenttopicprogress_and_more'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('TOPIC_PRACTICE', 'Topic practice'), ('CHAPTER_TEST', 'Chapter test'), ('MOCK_EXAM', 'Mock exam')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=150)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='users.teacher')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='planner.chapter')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='planner.topic')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=12)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='users.student')),
            ],
            options={
                'ordering': ['-started_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('partial_score', models.FloatField(default=0.0)),
                ('time_spent_s', models.PositiveIntegerField(blank=True, null=True)),
                ('hint_used', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('misconception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_answers', to='assessment.misconception')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='assessment.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.quizattempt')),
            ],
            options={
                'ordering': ['question_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('QUIZ', 'Quiz'), ('FLASHCARD', 'Flashcard'), ('PLANNER_EXERCISE', 'Planner exercise'), ('TEACHER_GRADE', 'Teacher grade')], max_length=20)),
                ('source_ref_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('difficulty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('occurred_at', models.DateTimeField()),
                ('weight_modifier', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='assessment.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='users.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='planner.topic')),
            ],
            options={
                'ordering': ['-occurred_at', 'id'],
                'indexes': [models.Index(fields=['student', 'topic', 'occurred_at'], name='assessment__student_17a237_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0), ('score__lte', 1)), name='assessment_evidence_score_range'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(check=models.Q(('weight_modifier__gte', 0)), name='assessment_evidence_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('source', 'source_ref_type', 'source_ref_id', 'question'), name='assessment_unique_evidence_per_source'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['kind', 'is_active'], name='assessment__kind_dbfe64_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz', 'status'], name='assessment__student_f0924d_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='assessment_unique_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.CheckConstraint(check=models.Q(('partial_score__gte', 0), ('partial_score__lte', 1)), name='assessment_attempt_answer_partial_score_range'),
        ),
    ]
