# Generated by Django 5.0.7 on 2026-10-06 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_quiz_quizattempt_attemptanswer_evidence_and_more'),
        ('planner', '0007_curriculumversion_chapter_topic_studenttopicprogress_and_more'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteryRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('json', models.JSONField(default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mastery', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='NONE', max_length=8)),
                ('trend', models.CharField(choices=[('UP', 'Up'), ('FLAT', 'Flat'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=8)),
                ('effective_weight', models.FloatField(default=0.0)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField()),
                ('rules_version', models.PositiveIntegerField(default=1)),
                ('reasons', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'topic mastery',
                'ordering': ['student', 'topic', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='masteryruleset',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='assessment_unique_mastery_ruleset_name_version'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mastery', to='users.student'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mastery', to='planner.topic'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['student', 'computed_at'], name='assessment__student_992fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['topic'], name='assessment__topic_i_e0589d_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.UniqueConstraint(fields=('student', 'topic'), name='assessment_unique_topic_mastery'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.CheckConstraint(check=models.Q(('mastery__isnull', True), models.Q(('mastery__gte', 0), ('mastery__lte', 1)), _connector='OR'), name='assessment_topic_mastery_range'),
        ),
    ]
