# Generated by Django 5.0.7 on 2026-10-06 18:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_masteryruleset_topicmastery_and_more'),
        ('planner', '0007_curriculumversion_chapter_topic_studenttopicprogress_and_more'),
        ('users', '0004_fieldofstudy_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardsRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('json', models.JSONField(default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'flashcard states',
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('front_ar', models.TextField(blank=True, default='')),
                ('front_fr', models.TextField(blank=True, default='')),
                ('back_ar', models.TextField(blank=True, default='')),
                ('back_fr', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assessment/flashcards/')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
                ('is_sample', models.BooleanField(default=False)),
                ('source_note', models.CharField(blank=True, default='', max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_flashcards', to='users.teacher')),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flashcards', to='planner.curriculumversion')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='planner.learningobjective')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flashcards', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flashcards', to='planner.topic')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.CharField(choices=[('AGAIN', 'Again'), ('HARD', 'Hard'), ('GOOD', 'Good'), ('EASY', 'Easy')], max_length=8)),
                ('reviewed_at', models.DateTimeField()),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('client_review_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='assessment.flashcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to='users.student')),
            ],
            options={
                'ordering': ['-reviewed_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='flashcardsruleset',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='assessment_unique_leitner_ruleset_name_version'),
        ),
        migrations.AddField(
            model_name='flashcardstate',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='assessment.flashcard'),
        ),
        migrations.AddField(
            model_name='flashcardstate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_states', to='users.student'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['topic', 'status'], name='assessment__topic_i_3aaea0_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['status'], name='assessment__status_679032_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['author'], name='assessment__author__1e0cc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.CheckConstraint(check=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='assessment_flashcard_difficulty_range'),
        ),
        migrations.AddIndex(
            model_name='flashcardreview',
            index=models.Index(fields=['student', 'card', 'reviewed_at'], name='assessment__student_cca63d_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashcardreview',
            constraint=models.UniqueConstraint(fields=('student', 'client_review_id'), name='assessment_unique_flashcard_review_client_id'),
        ),
        migrations.AddIndex(
            model_name='flashcardstate',
            index=models.Index(fields=['student', 'due_at'], name='assessment__student_b0dd59_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardstate',
            index=models.Index(fields=['student', 'card'], name='assessment__student_01da66_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashcardstate',
            constraint=models.UniqueConstraint(fields=('student', 'card'), name='assessment_unique_flashcard_state'),
        ),
        migrations.AddConstraint(
            model_name='flashcardstate',
            constraint=models.CheckConstraint(check=models.Q(('box__gte', 1)), name='assessment_flashcard_state_box_positive'),
        ),
    ]
