# Generated by Django 5.0.7 on 2026-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_flashcardsruleset_flashcardstate_flashcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='adaptive_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
