# Generated by Django 5.0.7 on 2026-10-07 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_quizattempt_adaptive_state'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100.0)),
                ('recorded_at', models.DateTimeField()),
                ('source_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student', 'subject', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['question', 'is_correct'], name='assessment__questio_b00529_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['misconception'], name='assessment__misconc_75b616_idx'),
        ),
        migrations.AddField(
            model_name='teachergrade',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_grades', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='teachergrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grades', to='users.student'),
        ),
        migrations.AddIndex(
            model_name='teachergrade',
            index=models.Index(fields=['subject'], name='assessment__subject_432d13_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachergrade',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='assessment_unique_teacher_grade'),
        ),
        migrations.AddConstraint(
            model_name='teachergrade',
            constraint=models.CheckConstraint(check=models.Q(('max_score__gt', 0), ('score__gte', 0)), name='assessment_teacher_grade_range'),
        ),
    ]
