# Generated by Django 5.2.17 on 2026-09-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='access_cutoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
