# Generated by Django 5.0.7 on 2026-09-30 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_uuid_fields'),
        ('media_assets', '0001_initial'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='media_assets.videoasset'),
        ),
        migrations.AddField(
            model_name='survey',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='kind',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('SURVEY', 'Survey')], default='SURVEY', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='passing_score_percent',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='survey',
            name='show_results',
            field=models.CharField(choices=[('IMMEDIATELY', 'Immediately'), ('AFTER_DEADLINE', 'After deadline'), ('NEVER', 'Never')], default='IMMEDIATELY', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='shuffle_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='expected_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple choice'), ('TRUE_FALSE', 'True / False'), ('SHORT_ANSWER', 'Short answer'), ('MULTIPLE_SELECT', 'Multiple select')], default='MULTIPLE_CHOICE', max_length=20),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.section'),
        ),
        migrations.CreateModel(
            name='SurveyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_attempts', to='users.student')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.survey')),
            ],
            options={
                'ordering': ['-submitted_at', '-attempt_number'],
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='courses.surveyattempt'),
        ),
    ]
