# Generated by Django 5.0.7 on 2026-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_duration_seconds_lesson_is_preview_and_more'),
        ('users', '0004_fieldofstudy_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyattempt',
            options={'ordering': ['attempt_number']},
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='last_position_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='surveyattempt',
            unique_together={('survey', 'student', 'attempt_number')},
        ),
    ]
