# Generated by Django 5.2.17 on 2026-09-28 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def fill_missing_meeting_times(apps, schema_editor):
    """start_time/end_time are becoming non-nullable; give historical rows a
    value so the NOT NULL constraint can be applied."""
    Meeting = apps.get_model("jitsi", "Meeting")
    now = timezone.now()
    Meeting.objects.filter(start_time__isnull=True).update(start_time=now)
    Meeting.objects.filter(end_time__isnull=True).update(end_time=now)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('groups', '0005_remove_scheduledtask_user_and_more'),
        ('jitsi', '0004_add_uuid_fields'),
        ('privetsessions', '0002_add_uuid_fields'),
        ('users', '0003_user_email_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='current_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(fill_missing_meeting_times, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='privetsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='privetsessions.privatesessionrequest', verbose_name='privetsessions'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='users.student'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
