# Generated by Django 5.0.7 on 2026-08-05 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('proposed_date', models.DateTimeField(blank=True, null=True)),
                ('is_paied', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('session_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='privetsessions.privatesessionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CheckSessionPaiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_image', models.ImageField(upload_to='checks/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_session_paiment', to=settings.AUTH_USER_MODEL)),
                ('PrivateSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_session_paiment', to='privetsessions.privatesessionrequest')),
            ],
        ),
    ]
