# Generated by Django 5.0.7 on 2026-08-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languagesteaching', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlanguageproficiency',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_proficiencies', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentlanguageproficiency',
            unique_together={('student', 'language')},
        ),
    ]
