# Generated by Django 5.0.7 on 2026-08-05 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('parent', 'ولي أمر')], default='student', max_length=10, verbose_name='الدور')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('family_name', models.CharField(max_length=100, verbose_name='اللقب')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{8,15}')], verbose_name='رقم الهاتف')),
                ('education_level', models.CharField(blank=True, choices=[('middle', 'متوسط'), ('high', 'ثانوي'), ('languages', 'دراسات لغات')], max_length=50, null=True, verbose_name='المستوى الدراسي')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='السنة الدراسية')),
                ('branch', models.CharField(blank=True, max_length=50, null=True, verbose_name='الشعبة')),
                ('language_choice', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللغة')),
                ('subjects', models.JSONField(default=list, verbose_name='المواد')),
            ],
            options={
                'verbose_name': 'استمارة الطالب',
                'verbose_name_plural': 'استمارات الطلاب',
            },
        ),
    ]
