"""Pure assessment engine (no Django, no DB, no network, no clock)."""

from .grading import (
    KIND_MCQ_MULTI,
    KIND_MCQ_SINGLE,
    KIND_NUMERIC,
    KIND_TRUE_FALSE,
    GradeResult,
    NumericKey,
    extract_numeric_value,
    extract_option_ids,
    grade,
    grade_choice,
    grade_numeric,
)
from .adaptive import (
    AdaptiveCandidate,
    AdaptiveDecision,
    AdaptiveState,
    apply_answer,
    select_next_question,
)
from .adaptive import Reason as AdaptiveReason
from .adaptive_rules import (
    ADAPTIVE_RULES_DIR,
    DEFAULT_ADAPTIVE_FILENAME,
    AdaptiveRules,
    load_adaptive_rules,
)
from .leitner import (
    LeitnerResult,
    LeitnerState,
    Reason as LeitnerReason,
    due_sort_key,
    is_due,
    next_state,
)
from .leitner_rules import (
    DEFAULT_LEITNER_FILENAME,
    LEITNER_RULES_DIR,
    RATINGS,
    RESET_DELTA,
    LeitnerRules,
    Rating,
    load_leitner_rules,
)
from .mastery import (
    EvidenceInput,
    Reason,
    TopicMasteryResult,
    compute_topic_mastery,
    evidence_from_rows,
)
from .mastery_rules import (
    DEFAULT_MASTERY_FILENAME,
    RULES_DIR,
    ConfidenceRules,
    MasteryConfidence,
    MasteryRules,
    ReadinessBand,
    ReadinessBands,
    ReadinessRules,
    RepeatCap,
    Trend,
    TrendRules,
    load_mastery_rules,
)
from .readiness import (
    BAND_NONE,
    ReadinessResult,
    TopicReadinessInput,
    compute_chapter_readiness,
    compute_readiness,
    compute_subject_readiness,
)
from .item_analysis import (
    FLAG_AMBIGUOUS_DISTRACTOR,
    FLAG_INSUFFICIENT_DATA,
    FLAG_LOW_DISCRIMINATION,
    FLAG_NEGATIVE_DISCRIMINATION,
    FLAG_TOO_EASY,
    FLAG_TOO_HARD,
    Flag,
    ItemAnalysisResult,
    ItemResponse,
    analyse_item,
)
from .item_analysis_rules import (
    DEFAULT_ITEM_ANALYSIS_FILENAME,
    ITEM_ANALYSIS_RULES_DIR,
    ItemAnalysisRules,
    load_item_analysis_rules,
)

__all__ = [
    "KIND_MCQ_MULTI",
    "KIND_MCQ_SINGLE",
    "KIND_NUMERIC",
    "KIND_TRUE_FALSE",
    "GradeResult",
    "NumericKey",
    "extract_numeric_value",
    "extract_option_ids",
    "grade",
    "grade_choice",
    "grade_numeric",
    # mastery
    "EvidenceInput",
    "Reason",
    "TopicMasteryResult",
    "compute_topic_mastery",
    "evidence_from_rows",
    "DEFAULT_MASTERY_FILENAME",
    "RULES_DIR",
    "ConfidenceRules",
    "MasteryConfidence",
    "MasteryRules",
    "ReadinessBand",
    "ReadinessBands",
    "ReadinessRules",
    "RepeatCap",
    "Trend",
    "TrendRules",
    "load_mastery_rules",
    # readiness
    "BAND_NONE",
    "ReadinessResult",
    "TopicReadinessInput",
    "compute_chapter_readiness",
    "compute_readiness",
    "compute_subject_readiness",
    # leitner / flashcards
    "LeitnerResult",
    "LeitnerState",
    "LeitnerReason",
    "due_sort_key",
    "is_due",
    "next_state",
    "DEFAULT_LEITNER_FILENAME",
    "LEITNER_RULES_DIR",
    "RATINGS",
    "RESET_DELTA",
    "LeitnerRules",
    "Rating",
    "load_leitner_rules",
    # adaptive
    "AdaptiveCandidate",
    "AdaptiveDecision",
    "AdaptiveState",
    "AdaptiveReason",
    "apply_answer",
    "select_next_question",
    "ADAPTIVE_RULES_DIR",
    "DEFAULT_ADAPTIVE_FILENAME",
    "AdaptiveRules",
    "load_adaptive_rules",
    # item analysis
    "FLAG_AMBIGUOUS_DISTRACTOR",
    "FLAG_INSUFFICIENT_DATA",
    "FLAG_LOW_DISCRIMINATION",
    "FLAG_NEGATIVE_DISCRIMINATION",
    "FLAG_TOO_EASY",
    "FLAG_TOO_HARD",
    "Flag",
    "ItemAnalysisResult",
    "ItemResponse",
    "analyse_item",
    "DEFAULT_ITEM_ANALYSIS_FILENAME",
    "ITEM_ANALYSIS_RULES_DIR",
    "ItemAnalysisRules",
    "load_item_analysis_rules",
]
