# Generated by Django 5.0.7 on 2026-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, choices=[('رياضيات', 'رياضيات'), ('فيزياء', 'فيزياء'), ('كيمياء', 'كيمياء'), ('أحياء', 'أحياء'), ('فرنسية', 'فرنسية'), ('عربية', 'عربية'), ('إنجليزية', 'إنجليزية'), ('تاريخ', 'تاريخ'), ('جغرافيا', 'جغرافيا'), ('فلسفة', 'فلسفة'), ('اقتصاد', 'اقتصاد')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
